workflows:
  android-debug-apk:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
    environment:
      java: 17
    scripts:
      - name: Create local.properties and Build
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          flutter clean
          flutter pub get
          cd android
          # Garante que o gradlew seja criado caso não exista
          gradle wrapper --gradle-version 8.3
          # Garante que o arquivo tenha permissão de execução
          chmod +x gradlew
          # Agora executa o clean e o assemble
          ./gradlew clean
          ./gradlew assembleDebug --no-daemon --info
