workflows:
  android-debug-apk:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
    environment:
      java: 17
    scripts:
      - name: Clean, Setup and Build
        script: |
          flutter clean
          flutter pub get
          cd android
          # Força o Gradle a usar o AndroidX e Jetifier para converter libs antigas
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          gradle wrapper --gradle-version 8.3
          ./gradlew assembleDebug --no-daemon --info
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
