workflows:
  android-debug-apk:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
    environment:
      java: 17
    scripts:
      - name: Build Android APK
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          flutter clean
          flutter pub get
          # Vamos forçar a atualização mínima necessária para o Firebase
          flutter pub upgrade firebase_core cloud_firestore
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk,
      
